name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Run the API
      if: github.ref == 'refs/heads/develop'
      run: |
        newman run "projeto_teste/Deck of Cards - API Tests.postman_collection.json"
