name: Test Workflow using Newman

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Run the Tests
        run: |
          newman run "projeto_teste/Deck of Cards - API Tests.postman_collection.json"
